# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: SaeraSoft.CaesiumImageCompressor
PackageVersion: 2.2.0
Installers:
- MinimumOSVersion: 10.0.0.0
  Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/Lymphatus/caesium-image-compressor/releases/download/v2.2.0/caesium-image-compressor-2.2.0-win-setup.exe
  InstallerSha256: 08029b96ee56bbf36734b72fb72f1b4dba49f1f531ba93c9cb50efeddbb189dd
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.1.0

